name: Release

on:
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: gradle

      - name: Extract version
        id: version
        run: |
          VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Validate release notes
        id: notes
        run: |
          FILE=".github/nextRelease.md"

          if [ ! -f "$FILE" ]; then
            echo "nextRelease.md must exist"
            exit 1
          fi

          CONTENT=$(cat "$FILE")

          if [ -z "$CONTENT" ]; then
            echo "nextRelease.md must not be empty."
            exit 1
          fi

          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release + upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          NOTES_FILE=".github/nextRelease.md"

          TAG="v$VERSION"

          gh release create "$TAG" \
            "./build/libs/"*.jar \
            --title "$VERSION" \
            --notes-file "$NOTES_FILE"

      - name: Clear nextRelease.md
        run: |
          echo "" > .github/nextRelease.md
          
          git config --global user.email "jigsawdb@not.existent"
          git config --global user.name "JigsawDB AutoPublish"

          git add .github/nextRelease.md
          git commit -m "chore: clear nextRelease.md after release" || exit 0
          git push

      - name: Publish to Maven Central
        run: ./gradlew publishToMavenCentral
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_TOKEN_USER }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
