name: Release
permissions:
  contents: write
on:
  push:
    branches:
      - main
    paths:
      - 'gradle.properties'
concurrency:
  group: release
  cancel-in-progress: false

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: "Preparation: Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Preparation: Make gradlew executable"
        run: chmod +x ./gradlew

      - name: "Preparation: Set up JDK"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: gradle

      - name: "Preparation: Extract version"
        id: version
        run: |
          VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: "Preparation: Validate release notes"
        id: notes
        run: |
          FILE=".github/nextRelease.md"

          if [ ! -f "$FILE" ]; then
            echo "nextRelease.md must exist"
            exit 1
          fi

          CONTENT=$(cat "$FILE")

          if [ -z "$CONTENT" ]; then
            echo "nextRelease.md must not be empty."
            exit 1
          fi

          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: "Release: Publish to Maven Central"
        run: ./gradlew publishAndReleaseToMavenCentral
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_TOKEN_USER }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: "Release: Create GitHub Release + upload assets"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          NOTES_FILE=".github/nextRelease.md"

          TAG="v$VERSION"

          gh release view "$TAG" >/dev/null 2>&1 && exit 0
          gh release create "$TAG" \
            "./build/libs/"*.jar \
            --title "$VERSION" \
            --notes-file "$NOTES_FILE"

      - name: "Release: Generate Javadocs"
        run: ./gradlew javadoc

      - name: "Release: Publish Javadocs branch"
        run: |
          DOCS_BRANCH="javadocs"
          DOCS_DIR="src/core/build/docs/javadoc"

          if [ ! -d "$DOCS_DIR" ]; then
            echo "Javadocs not generated"
            exit 1
          fi

          TEMP_DIR=$(mktemp -d)

          cp -R "$DOCS_DIR"/. "$TEMP_DIR"/

          git fetch origin

          if git ls-remote --exit-code --heads origin "$DOCS_BRANCH"; then
            git checkout "$DOCS_BRANCH"
          else
            git checkout --orphan "$DOCS_BRANCH"
          fi

          find . -mindepth 1 -maxdepth 1 \
            ! -name 'CNAME' \
            ! -name '.git' \
            -exec rm -rf {} +

          cp -R "$TEMP_DIR"/. .

          touch .nojekyll

          git add -A

          if git diff --cached --quiet; then
            echo "No Javadocs changes"
            exit 0
          fi

          git commit -m "[BOT] Update Javadocs for v${{ steps.version.outputs.version }}"
          git push origin "$DOCS_BRANCH" --force

      - name: "Cleanup: Update version in files"
        run: |
          VERSION=${{ steps.version.outputs.version }}

          grep -rl '<!--VERSION-->' . | grep -v 'gradle.properties' | while read file; do
            sed -i -E "s|(<!--VERSION-->)[^<]*(<!--END_VERSION-->)|\1${VERSION}\2|g" "$file"
          done

      - name: "Cleanup: Clear nextRelease.md"
        run: |
          cp .github/assets/nextRelease.md.template .github/nextRelease.md

      - name: "Cleanup: Push changes"
        run: |
          git config --global user.email "jigsawdb@not.existent"
          git config --global user.name "JigsawDB Version Update"
          git checkout -B "${GITHUB_REF_NAME}"

          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git add -A
          git commit -am "[BOT] Update version to v${{ steps.version.outputs.version }}"
          
          git push
